version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: 'lib/nile'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: 'packages/examples'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: 'packages/react'
    schedule:
      interval: 'weekly'
