#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged 
yarn workspace @theniledev/react test
yarn workspace @theniledev/js test
yarn workspace @theniledev/server test
yarn workspace @theniledev/browser test
