name: Publish @theniledev packages to GitHub Packages

on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: stable

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          # registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@theniledev'
      - name: Authenticate to npm
        run: |
          echo "@theniledev:wq:registry=https://registry.npmjs.org/" 
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install @theniledev/js
        working-directory: lib/nile
        run: yarn install --no-lockfile

      - name: Install @theniledev/react
        working-directory: packages/react
        run: yarn install --no-lockfile

      - name: Build @theniledev/packages
        run: yarn build

      - name: Version
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npx lerna version --force-publish --conventional-commits --yes

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx lerna publish from-git --yes
